const hospitals = [
  {
    id: 1,
    name: '北京协和医院',
    level: '三甲',
    city: '北京',
    departments: ['神经内科', '心内科', '消化内科'],
    distance: '距您约3.2公里',
    description: '综合实力全国顶尖，疑难重症首选',
  },
  {
    id: 2,
    name: '北京安贞医院',
    level: '三甲',
    city: '北京',
    departments: ['心内科', '心外科'],
    distance: '距您约4.1公里',
    description: '心血管疾病专科权威医院',
  },
  {
    id: 3,
    name: '北京大学人民医院',
    level: '三甲',
    city: '北京',
    departments: ['神经内科', '普外科', '消化内科'],
    distance: '距您约5.6公里',
    description: '综合性研究型医院，科室齐全',
  },
  {
    id: 4,
    name: '复旦大学附属中山医院',
    level: '三甲',
    city: '上海',
    departments: ['心内科', '消化内科', '普外科'],
    distance: '距您约2.8公里',
    description: '华东地区综合实力领先',
  },
  {
    id: 5,
    name: '上海瑞金医院',
    level: '三甲',
    city: '上海',
    departments: ['神经内科', '消化内科'],
    distance: '距您约3.5公里',
    description: '老字号名院，慢性病管理经验丰富',
  },
  {
    id: 6,
    name: '深圳市人民医院',
    level: '三甲',
    city: '深圳',
    departments: ['神经内科', '心内科', '普外科'],
    distance: '距您约1.9公里',
    description: '深圳规模最大的综合性医院',
  },
  {
    id: 7,
    name: '北京大学深圳医院',
    level: '三甲',
    city: '深圳',
    departments: ['消化内科', '心内科', '普外科'],
    distance: '距您约4公里',
    description: '学术背景扎实，综合诊疗能力强',
  },
  {
    id: 8,
    name: '北京市海淀医院',
    level: '二甲',
    city: '北京',
    departments: ['心内科', '消化内科', '全科'],
    distance: '距您约1.8公里',
    description: '社区综合医院，日常就诊便捷',
  },
  {
    id: 9,
    name: '北京市朝阳区第二医院',
    level: '二甲',
    city: '北京',
    departments: ['消化内科', '全科', '内科'],
    distance: '距您约2.1公里',
    description: '区级综合医院，常见病诊疗经验丰富',
  },
  {
    id: 10,
    name: '上海市杨浦区中心医院',
    level: '二甲',
    city: '上海',
    departments: ['心内科', '消化内科', '全科'],
    distance: '距您约1.5公里',
    description: '区域综合医院，就诊等待时间短',
  },
  {
    id: 11,
    name: '深圳市龙华区人民医院',
    level: '二甲',
    city: '深圳',
    departments: ['心内科', '消化内科', '全科'],
    distance: '距您约1.6公里',
    description: '区级综合医院，综合诊疗能力稳定',
  },
]

export default hospitals
